server:
  port: 9090
spring:
  application:
    name: InventoryService
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id: InventoryService
    servers: localhost:8124