kind: ConfigMap 
apiVersion: v1 
metadata:
  name: shipment-configmap
data:
  # Configuration values can be set as key-value properties
  MYSQL_HOST: 35.231.178.113
  AXON_HOST: 34.23.126.183:8124
  GCP_PROJECT_ID: boreal-gravity-396810
  PUB_SUB_TOPIC_ID: PUB_SUB_TOPIC_ID
