apiVersion: v1
kind: Service
metadata:
  name: shipmentservice
  labels:
    app: shipmentservice
spec:
  ports:
    - name: http
      port: 9093
      targetPort: 9093
  selector:
    app: shipmentservice
  type: LoadBalancer