apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipmentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipmentservice
  template:
    metadata:
      labels:
        app: shipmentservice
    spec:
      containers:
        - name: shipmentservice
          image: your-acr-name.azurecr.io/your-image-name

          ports:
            - containerPort: 9093

