apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: your-acr-name.azurecr.io/your-image-name

          ports:
            - containerPort: 9090


---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: LoadBalancer
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
