apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: cartservice
  type: LoadBalancer