server:
  port: 9090
spring:
  application:
  name: ShipmentService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shipment_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id: OrderService
    servers: localhost:8124
