kind: ConfigMap 
apiVersion: v1 
metadata:
  name: orderservice-configmap
data:
  # Configuration values can be set as key-value properties
  MYSQL_HOST: 35.231.178.113
  AXON_HOST: 34.23.126.183:8124
