apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                name: cardemo-secret
                key: cardemo-db-username
                optional: false
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                  name: cardemo-secret
                  key: cardemo-db-userpassword
                  optional: false
          envFrom:
            - configMapRef:
                name: orderservice-configmap
