apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
images:
- name: gcr.io/PROJECT_ID/IMAGE:TAG
  newName: gcr.io/boreal-gravity-396810/orderservice
  newTag: 1.0.1
