apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: car-demo-order-secretstore
  namespace: default
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: boreal-gravity-396810
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-demo-externalsecret
  namespace: default
spec:
  secretStoreRef:
    name: car-demo-order-secretstore
    kind: SecretStore
  target:
    name: secret-to-be-created
  data:
    - secretKey: "mysql-db-username"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-username
    - secretKey: "mysql-db-userpassword"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-userpassword

    - secretKey: "MY_SQL_SECRETS"
      remoteRef:
        key: car-demo-secret
        version: latest