apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: your-acr-name.azurecr.io/your-image-name

          ports:
            - containerPort: 9092


---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: LoadBalancer
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092