server:
  port: 9092
spring:
  application:
  name: PaymentService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payment_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id: PaymentService
    servers: ${AXON_HOST}