server:
  port: 9092
spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payment_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    client-id: PaymentService
    servers: ${AXON_HOST:localhost:8124}
