apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
        - name: adminservice
          image: your-acr-name.azurecr.io/your-image-name

          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminservice
spec:
  type: LoadBalancer
  selector:
    app: adminservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
