server:
  port: 9090
spring:
  application:
  name: OrderService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/orders_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USER}
    password: ${MY_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
  axonserver:
    client-id: OrderService
    servers: ${AXON_HOST}
# Possible values for these keys are `default`, `xstream`, `java`, and `jackson`.
  serializer:
    general: default
    events: jackson
    messages: jackson
