server:
  port: 9090
spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/order_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
  axonserver:
    client-id: OrderService
    servers: ${AXON_HOST:localhost:8124}
