apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9092
              protocol: TCP
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-username
                  optional: false
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-userpassword
                  optional: false
          envFrom:
            - configMapRef:
                name: payment-configmap
