apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  ports:
    - name: http
      port: 9092
      targetPort: 9092
  selector:
    app: paymentservice
  type: LoadBalancer