apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
        - name: adminservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
          env:
          # Add environment variables here, if needed
          resources:
          # Set resource limits and requests, if needed
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: adminservice
spec:
  selector:
    app: adminservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer