server:
  port: 9090
spring:
  application:
  name: OrderService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/order_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
  axonserver:
    client-id: OrderService
    servers: ${AXON_HOST}

