server:
  port: 9096
spring:
  application:
  name: CartService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlpassword
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update