pubSub:
  topic: java-competency
  subscriptionId: java-competency-sub
  projectId: oval-crawler-398007
  credentials: oval-crawler-398007-406ca3b3a9ba.json

elastic:
  hostname: ${HOSTNAME:35.201.207.148}
  port: ${PORT:9200}








