apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: your-acr-name.azurecr.io/your-image-name

          ports:
            - containerPort: 9091


---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
spec:
  type: LoadBalancer
  selector:
    app: inventoryservice
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
