name: GCP Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: SonarCloud Scan
        run: |
          cat projects-changes-deploy.txt | while read repo; do
            echo "Processing repository: $repo"
            cd $repo
            #mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech -Dsonar.branch.name=master

            # Check if it's the Angular project (car-ui)
            if [ "$repo" == "car-ui" ]; then
              # Angular-specific commands
              npm install
              
              # Run tests and generate code coverage reports
              npm run test -- --coverage
              
              # Install SonarScanner for Node.js
              npm install -g sonarqube-scanner
              
              # Run SonarScanner for Node.js
              sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech -Dsonar.branch.name=master
            else
              # Maven-specific commands
              mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech -Dsonar.branch.name=master
            fi

            
            cd ..
          done        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
