name: car-demo-common-service

on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/labeler@v4
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_KEY }}'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GKE_PROJECT }}

        # Configure Docker to use the gcloud command-line tool as a credential
        # helper for authentication
      - name: configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build, Publish, and Deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          . apps-deployment-script.sh "us-east1"