name: car-demo-common-service

on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_KEY }}
          export_default_credentials: true

        # Configure Docker to use the gcloud command-line tool as a credential
        # helper for authentication
      - name: configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build, Publish, and Deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          . service-deploy.sh ${{ env.GKE_PROJECT }}