apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-ui
  template:
    metadata:
      labels:
        app: car-ui
    spec:
      containers:
        - name: car-ui
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: car-ui-app
spec:
  selector:
    app: car-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer