apiVersion: apps/v1
kind: Deployment
metadata:
  name: carui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carui
  template:
    metadata:
      labels:
        app: carui
    spec:
      containers:
        - name: carui
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: carui
spec:
  selector:
    app: carui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
