apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-username
                  optional: false
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-userpassword
                  optional: false
          envFrom:
            - configMapRef:
                name: inventory-configmap