apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-username
                  optional: false
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: mysql-db-userpassword
                  optional: false
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: gcp_json_key
                  optional: false
          envFrom:
            - configMapRef:
                name: inventory-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  selector:
    app: inventoryservice
  type: LoadBalancer

---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: car-demo-inventory-secretstore
  namespace: default
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: datamesh-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-demo-externalsecret
  namespace: default
spec:
  secretStoreRef:
    name: car-demo-inventory-secretstore
    kind: SecretStore
  target:
    name: secret-to-be-created
  data:
    - secretKey: "mysql-db-username"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-username
    - secretKey: "mysql-db-userpassword"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: mysql-db-userpassword
    - secretKey: "gcp_json_key"
      remoteRef:
        key: car-demo-secret
        version: latest
        property: gcp_json_key

    - secretKey: "MY_SQL_SECRETS"
      remoteRef:
        key: car-demo-secret
        version: latest

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: inventory-configmap
data:
  # Configuration values can be set as key-value properties
  MYSQL_HOST: 34.138.37.73
  AXON_HOST: 34.139.102.42:8124
  SERVICE_NAME: InventoryService
  GCP_PROJECT_ID: datamesh-2
  PRODUCT_SUBSCRIPTION: inventory_subscription
