apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
  labels:
    app: inventoryservice
spec:
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  selector:
    app: inventoryservice
  type: LoadBalancer